package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/proveo-ca/proveo/internal/provider"
	"github.com/proveo-ca/proveo/internal/ui"
)

// initProviderKeys are env vars proveo --init may copy into a new .env.
// Includes broker KeyVars plus common aliases the bash init shipped.
var initProviderKeys = func() []string {
	seen := map[string]bool{}
	var out []string
	add := func(k string) {
		if seen[k] {
			return
		}
		seen[k] = true
		out = append(out, k)
	}
	for _, k := range provider.KeyVars() {
		add(k)
	}
	for _, k := range []string{
		"OPENROUTER_API_KEY", "DEEPSEEK_API_KEY", "HUGGINGFACE_API_KEY", "HF_TOKEN",
		"GOOGLE_API_KEY", "CURSOR_API_KEY",
	} {
		add(k)
	}
	return out
}()

// initCmd keeps `proveo init` as an alias for `proveo --init`.
func initCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Create a project .env from provider API keys already in the environment (alias for --init)",
		Args:  cobra.NoArgs,
		RunE:  func(*cobra.Command, []string) error { return doInit() },
	}
}

func doInit() error {
	envFile := os.Getenv("PROVEO_ENV_FILE")
	if envFile == "" {
		envFile = ".env"
	}
	if _, err := os.Stat(envFile); err == nil {
		ui.Okf("Found existing %s; leaving it unchanged.", envFile)
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}

	var found []string
	vals := map[string]string{}
	for _, k := range initProviderKeys {
		if v := strings.TrimSpace(os.Getenv(k)); v != "" {
			found = append(found, k)
			vals[k] = v
		}
	}
	if len(found) == 0 {
		ui.Failf("No LLM API provider keys found in the current environment.")
		ui.Notef("Set one of these before running 'proveo --init':")
		for _, k := range initProviderKeys {
			ui.Notef("  %s", k)
		}
		return fmt.Errorf("no provider keys in environment")
	}

	var b strings.Builder
	b.WriteString("# Generated by proveo --init from API keys in the host environment.\n")
	for _, k := range found {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(quoteEnvValue(vals[k]))
		b.WriteByte('\n')
	}
	b.WriteString("ATTACH_RTK=false\n")

	if err := os.WriteFile(envFile, []byte(b.String()), 0o600); err != nil {
		return err
	}
	ui.Okf("Created %s with %d provider key(s): %s", envFile, len(found), strings.Join(found, " "))
	return nil
}

// quoteEnvValue produces a shell-safe single-token value (bash printf %q–like).
func quoteEnvValue(v string) string {
	return strconv.Quote(v)
}
